language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - "pip install coveralls"
  - "pip install -r requirements.txt"
script:
  coverage run --source=ssh_foward_proxy setup.py test
after_success:
  coveralls
